Repository merta1/CSE442_Project, pull requests merged in 2019-03, with the labels that each got.

#61 Fix nav
  react/debate-frontend/src/App.js
  react/debate-frontend/src/Form.js
  react/debate-frontend/src/Nav.js
  react/debate-frontend/src/Registration.js
  react/debate-frontend/src/index.css
Labels: bug, enhancement, task

#63 make direct urls work closes #51 #47
  react/debate-frontend/src/App.js
  react/debate-frontend/src/Nav.js
  react/debate-frontend/src/Register.js
Labels: bug, enhancement, task

#64 Debate window improvements
  react/debate-frontend/src/CommentItem.js
  react/debate-frontend/src/DebateWindow.js
Labels: bug, enhancement, task

#65 Realistic data
  react/debate-frontend/src/DebateList.js
  react/debate-frontend/src/DebateWindow.js
Labels: task

#66 Registerlocalstorage
  react/debate-frontend/src/App.js
  react/debate-frontend/src/Nav.js
  react/debate-frontend/src/Register.js
Labels: task

#67 fix compiler error in register.js"
  react/debate-frontend/src/Register.js
Labels: bug

#70 Jon end of sprint
  react/debate-frontend/src/App.js
  react/debate-frontend/src/DebateWindow.js
  react/debate-frontend/src/Nav.js
  react/debate-frontend/src/Register.js
Labels: task

#75 prevent page refresh closes #73
  react/debate-frontend/src/Register.js
Labels: bug

#76 Release 1.0.1 Minor Bug Fix
  react/debate-frontend/src/Register.js
Labels: bug
